resources:
  - name: redis_image
    type: image
    integration: dockerhub-ric03uec
    pointer:
      sourceName: "library/consul"
    seed:
      versionName: latest

  - name: nginx_image
    type: image
    integration: dockerhub-ric03uec
    pointer:
      sourceName: "library/nginx"
    seed:
      versionName: latest

# Default docker option used to run the container is -d, containers MUST run in
# background else, they'll block the calling process
# Other options can be configured from yml
jobs:
  - name: link_images
    type: runSh
    links:
      # TODO: the image tags and name should be evaluated from "resource"
      - image: library/consul
        tag: latest
        name: "my-consul"
        options: "--publish 8500:8500"
      - image: library/nginx
        tag: latest
        name: "my-nginx"
        options: "--publish 8181:80"
    steps:
      - TASK:
          script:
            - uname -a
            - echo "Response from nginx container"
            - sleep 30
            - curl -XGET http://my-nginx:80
            - echo "=============================="
            - echo "Respose from consul container
            - curl -XGET http://my-consul:8500
            - echo "=============================="
